#!/bin/bash

#-----------------------------------------------------------------------------
[[ -x $(command -v linode-cli 2> /dev/null) ]] || {
  echo "This script depends on linode-cli and it is not available." >&2
  exit 1
}

(($#)) || {
  echo "Must pass the name of the script you want to update." >&2
  exit 1
}

name="$1"

#-----------------------------------------------------------------------------
filename="scripts/$name"

[[ -r $filename ]] || {
  echo "$filename is not a file or is not accessible"
  exit 1
}

#-----------------------------------------------------------------------------
# determine action
# if scriptid exists in file, we're updating
# otherwise we're creating
# The format is '# scriptid: ###'
# Nothing else is allowed on this line, spaces are ignored.

rx='^[[:space:]]*#[[:space:]]*scriptid:[[:space:]]*[[:digit:]]+[[:space:]]*$'
scriptid="$(grep -Ei "$rx" "$filename" | awk '{print $3}')"

action='create'
[[ -n $scriptid ]] && action='update'

#-----------------------------------------------------------------------------
distro="$(linode-cli images list --label 'Arch Linux' --text --no-headers | cut -f 1)"

#-----------------------------------------------------------------------------
# parse description from ABSTRACT section of stackscript
description="$(awk '/: << ABSTRACT/{flag=1; next} /ABSTRACT/{flag=0} flag' "$filename")"

[[ -z $description ]] && {
  echo "Could not find description in $filename"
  exit 1
}

#-----------------------------------------------------------------------------
declare -a lcopt

lcopt+=('stackscripts')
lcopt+=("$action")
[[ -n $scriptid ]] && lcopt+=("$scriptid")
lcopt+=('--label' "$name")
lcopt+=('--images' "$distro")
lcopt+=('--is_public' 'true')
lcopt+=('--script' "$(< "$filename")")
lcopt+=('--description' "$description")

((DEBUG)) && echo linode-cli "${lcopt[@]}"
linode-cli "${lcopt[@]}"
