#!/bin/bash

# linode-stackscript -a update -d archlinux -p true -D 'Minimal Arch Linux: wheel group can sudo; reflector, ufw, git installed; system tweaked' -c minimal_arch -l minimal_arch '

stackscriptid="335947"
distro='Arch Linux'
name='arch_bash_library'

filename="./$name"

[[ -f $filename ]] || {
  echo "$filename is not a file"
  exit 1
}

# parse description from ABSTRACT section of stackscript

description="This does nothing by itself. This is a library of functions I am
using in my 'mininal_arch' stackscript. You are welcome to use it.

Source this in your arch stackscript by doing the following:

  source <ssinclude StackScriptID='$stackscriptid'>"

declare -a lsopt

lsopt=('--label' "$name")
lsopt+=('--distribution' "$distro")
lsopt+=('--codefile' "$filename")
lsopt+=('--ispublic' 'true')
#lsopt+=('--description' "'$description'")
lsopt+=('--description')

# shellcheck disable=SC2068
linode-stackscript -a update ${lsopt[@]} "$description"
