#!/bin/bash

[[ -x $(command -v linode-stackscript 2> /dev/null) ]] || {
  echo "This script depends on linode-stackscript and it is not available." >&2
  exit 1
}

distro='Arch Linux'
name='minimal_arch'

filename="./$name"

[[ -f $filename ]] || {
  echo "$filename is not a file"
  exit 1
}

# parse description from ABSTRACT section of stackscript
description="$(awk '/: << ABSTRACT/{flag=1; next} /ABSTRACT/{flag=0} flag' $filename)"

declare -a lsopt

lsopt=('--label' "$name")
lsopt+=('--distribution' "$distro")
lsopt+=('--codefile' "$filename")
lsopt+=('--ispublic' 'true')
lsopt+=('--description')

# shellcheck disable=SC2068
linode-stackscript -a update ${lsopt[@]} "$description"
